Issue with not ready result_value
If value is not ready, library returns:
```
taskiq_result: TaskiqResult[_ReturnType] = pickle.loads(result_value)
TypeError: a bytes-like object is required, not 'NoneType'
```
Now it will return real error